---
- name: create swap file
  shell:
    cmd: |
      set -e
      fallocate -l {{ size }} {{ swapfile }}
      mkswap {{ swapfile }}
    creates: "{{ swapfile }}"

- name: swap file perms
  file:
    path: "{{ swapfile }}"
    owner: root
    group: root
    mode: 0600

- name: check swap file usage  # noqa: 301
  command: swapon
  register: swapfile_used
  changed_when: false

- name: enable swap file usage
  command: swapon {{ swapfile }}
  when: swapfile not in swapfile_used.stdout

- name: swap file fstab entry
  mount:
    name: none
    src: "{{ swapfile }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
