---
scrape_configs:
  # Prometheus itself.
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

  - job_name: sner-local
    scheme: https
    metrics_path: /sner/api/v1/stats/prometheus
    static_configs:
      - targets: ['localhost']
    tls_config:
      insecure_skip_verify: true
