---
- name: install deps
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present

- name: add repo key
  apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add repo
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
