---
- name: install deps
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present

- name: add repo key
  apt_key:
    id: 8C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add repo
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: install packages
  apt:
    name: grafana
    state: present

- name: configure grafana-server listener
  ini_file:
    path: /etc/grafana/grafana.ini
    section: server
    option: "{{ item['key'] }}"
    value: "{{ item['val'] }}"
  loop:
    - {key: http_addr, val: 127.0.0.1}
    - {key: root_url, val: "https://{{ ansible_fqdn }}/grafana"}
    - {key: serve_from_sub_path, val: 'true'}
  notify: restart grafana-server

- name: set admin secret
  shell:
    cmd: |
      sudo -u grafana grafana-cli admin reset-admin-password {{ grafana_admin_password }}
      touch .sner-ansible.grafana_admin_password
    chdir: /opt/sner
    creates: /opt/sner/.sner-ansible.grafana_admin_password

- name: configure grafana reverse proxy
  copy:
    content: |
      ProxyPass /grafana http://127.0.0.1:3000/grafana
      ProxyPassReverse /grafana http://127.0.0.1:3000/grafana
    dest: /etc/apache2/conf-enabled/grafana.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2

- name: enable and start grafana-server
  service:
    name: grafana-server
    enabled: true
    state: started

- name: check datasource exist
  uri:
    url: 'http://127.0.0.1:3000/api/datasources/name/prometheus'
    user: admin
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
    status_code: [200, 404]
  register: datasource_exist

- name: create datasource
  vars:
    create_request:
      name: prometheus
      type: prometheus
      url: http://127.0.0.1:9090
      access: proxy
      isDefault: true
  uri:
    url: 'http://127.0.0.1:3000/api/datasources'
    method: POST
    user: admin
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
    body_format: json
    body: "{{ create_request }}"
  when: datasource_exist.status == 404

- name: import dashboards
  include_tasks: grafana_import_dashboard.yml
  with_fileglob: 'files/grafana-dashboards/*.json'
