---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: restart prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted

- name: restart grafana-server
  service:
    name: grafana-server
    state: restarted
