{
 "title": "dash1",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "storage stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sner_storage_hosts_total{job=\"sner-server\"}",
     "legendFormat": "hosts"
    },
    {
     "expr": "sner_storage_services_total{job=\"sner-server\"}",
     "legendFormat": "services"
    },
    {
     "expr": "sner_storage_vulns_total{job=\"sner-server\"}",
     "legendFormat": "vulns"
    },
    {
     "expr": "sner_storage_notes_total{job=\"sner-server\"}",
     "legendFormat": "notes"
    }
   ]
  },
  {
   "title": "job stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sner_scheduler_jobs_total{job=\"sner-server\"}",
     "legendFormat": "jobs {{state}}"
    }
   ]
  },
  {
   "title": "storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sner_storage_hosts_total{job=\"sner-server\"}",
     "legendFormat": "hosts"
    },
    {
     "expr": "sner_storage_notes_total{job=\"sner-server\"}",
     "legendFormat": "notes"
    },
    {
     "expr": "sner_storage_services_total{job=\"sner-server\"}",
     "legendFormat": "services"
    }
   ]
  },
  {
   "title": "jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sner_scheduler_jobs_total{job=\"sner-server\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sner_scheduler_queue_targets_total{job=\"sner-server\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}