---
- name: install package
  apt:
    name: elasticsearch
    state: present

- name: set heap size
  copy:
    content: |
      -Xms{{ heap_size }}
      -Xmx{{ heap_size }}
    dest: /etc/elasticsearch/jvm.options.d/heap_size.options
    owner: root
    group: root
    mode: 0644
  when: heap_size is defined
  notify: restart elasticsearch

- name: run service
  service:
    name: elasticsearch
    enabled: true
    state: started
