---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: newaliases
  command: /usr/bin/newaliases

- name: generate locales
  command: /usr/sbin/locale-gen

- name: reload sysctl hardnet
  command: "/sbin/sysctl --load={{ sysctl_hardnet_file }}"
