---
- name: install deps
  apt:
    name: python3-passlib
    state: present

- name: ensure first user
  htpasswd:
    path: /etc/apache2/htpasswd
    username: "{{ user }}"
    password: "{{ password }}"
    owner: root
    group: www-data
    mode: 0640
  no_log: true

- name: require basicauth
  copy:
    content: |
      <Location />
        AuthType basic
        AuthName "authentication required"
        AuthUserFile /etc/apache2/htpasswd
        Require valid-user
      </Location>
    dest: /etc/apache2/conf-enabled/zz_basicauth.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
