---
- name: install deps
  apt:
    name:
      - git
      - sudo
      - make

- name: checkout from git
  git:
    repo: "{{ sner_repo }}"
    dest: /opt/sner
    version: "{{ sner_branch }}"

- name: create venv and install dependencies
  shell:
    cmd: |
      set -e
      make install
      touch .sner-ansible.install
    chdir: /opt/sner
    creates: /opt/sner/.sner-ansible.install
