---
scrape_configs:
  # prometheus itself (default)
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  # prometheus local node exporter (default)
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
    file_sd_configs:
      - files:
          - '/etc/prometheus/conf.d/node_*.yml'

  # sner-server
  - job_name: sner-server
    metrics_path: /sner/api/v2/stats/prometheus
    static_configs:
      - targets: ['localhost']

#  # Development Server
#  - job_name: sner-devserver
#    metrics_path: /api/v2/stats/prometheus
#    static_configs:
#      - targets: ['localhost:18000']
