---
- name: install iptables
  apt:
    name:
      - netfilter-persistent
      - iptables-persistent
    state: present

- name: configure iptables
  copy:
    src: "{{ lookup('first_found', rulesets) }}"
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0644
  vars:
    rulesets:
      - "{{ rules_v4 }}"
      - "rules.v4-{{ ansible_facts['fqdn'] }}"
      - "rules.v4-default"
  notify:
    - restart netfilter-persistent

- name: configure ip6tables
  copy:
    src: "{{ lookup('first_found', rulesets) }}"
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: 0644
  vars:
    rulesets:
      - "{{ rules_v6 }}"
      - "rules.v6-{{ ansible_facts['fqdn'] }}"
      - "rules.v6-default"
  notify:
    - restart netfilter-persistent
