---
- name: checkout from git
  git:
    repo: "{{ repo }}"
    version: "{{ branch }}"
    dest: "/opt/cvesearch"
    update: false

- name: read system requirements
  set_fact:
    required_packages: "{{ lookup('file', '/opt/cvesearch/requirements.system').splitlines() }}"

- name: system deps
  apt:
    name: "{{ item }}"
  loop:
    - "{{ required_packages }}"
    - python3-virtualenv

- name: python deps
  pip:
    requirements: "/opt/cvesearch/requirements.txt"
    virtualenv: "/opt/cvesearch/venv"
    virtualenv_python: python3

- name: config file
  copy:
    src: files/configuration.ini
    dest: "/opt/cvesearch/etc/configuration.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart uwsgi

- name: system integration paths
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: adm
    mode: 0755
  loop:
    - /var/lib/cvesearch
    - /var/log/cvesearch

- name: monkyepatch fs for logger
  file:
    src: /var/log/cvesearch
    dest: /opt/cvesearch/log
    state: link

- name: enable db update
  cron:
    name: cvesearch db update
    minute: '1'
    hour: '3'
    job: '/opt/cvesearch/venv/bin/python /opt/cvesearch/sbin/db_updater.py -v 1>/dev/null'

- name: install uwsgi container
  package:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: configure uwsgi
  copy:
    src: files/uwsgi-cvesearch.ini
    dest: /etc/uwsgi/apps-enabled/cvesearch.ini
    owner: root
    group: root
    mode: 0644
  notify: restart uwsgi

- name: http proxy cvesearch
  block:
    - name: install uwsgi proxy
      package:
        name: libapache2-mod-proxy-uwsgi
        state: present

    - name: enable uwsgi module
      apache2_module:
        name: proxy_uwsgi
        state: present
      notify: restart apache2

    - name: http proxy cvesearch
      copy:
        content: |
          ProxyPass /cvesearch unix:/var/run/uwsgi/app/cvesearch/socket|uwsgi://uwsgi-cvesearch/
        dest: /etc/apache2/conf-enabled/cvesearch.conf
        owner: root
        group: root
        mode: 0644
      notify: restart apache2
  when: enable_proxy
