---
- name: set hostname from default ipv4 addr ptr
  hosts: localhost

  tasks:
    - name: required packages
      apt:
        name:
          - python3-dnspython
        state: present

    - name: fqdn from dns
      set_fact:
        ptr_fqdn: "{{ lookup('dig', ansible_facts['default_ipv4']['address'] + '/PTR')[:-1] }}"

    - name: hostname from dns
      set_fact:
        ptr_hostname: "{{ ptr_fqdn.split('.')[0] }}"

    - name: set hostname
      hostname:
        name: "{{ ptr_hostname }}"

    - name: setup etc/hosts
      copy:
        content: |
          # managed file
          127.0.0.1 localhost
          ::1 localhost ip6-localhost ip6-loopback
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters
          {{ ansible_facts['default_ipv4']['address'] }} {{ ptr_fqdn }} {{ ptr_hostname }}
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
