---
- name: install deps
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present

- name: add repo key
  apt_key:
    id: 8C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add repo
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: install packages
  apt:
    name: grafana
    state: present

- name: configure grafana-server listener
  ini_file:
    path: /etc/grafana/grafana.ini
    section: server
    option: "{{ item['key'] }}"
    value: "{{ item['val'] }}"
    owner: root
    group: grafana
    mode: 0640
  loop:
    - {key: http_addr, val: 127.0.0.1}
    - {key: root_url, val: "https://{{ ansible_facts['fqdn'] }}/grafana"}
    - {key: serve_from_sub_path, val: 'true'}
  notify: restart grafana-server

- name: set admin secret
  shell:
    cmd: |
      sudo -u grafana grafana-cli admin reset-admin-password {{ grafana_admin_password }}
      touch .sner-ansible.grafana_admin_password
    chdir: /opt/sner
    creates: /opt/sner/.sner-ansible.grafana_admin_password

- name: provision datasource
  copy:
    src: files/grafana-datasource-prometheus.yml
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: root
    group: root
    mode: 0644
  notify: restart grafana-server

- name: provision dashboards provider
  copy:
    src: files/grafana-dashboards-default.yml
    dest: /etc/grafana/provisioning/dashboards/default.yml
    owner: root
    group: root
    mode: 0644
  notify: restart grafana-server

- name: create dashboards provisioning directory
  copy:
    src: "{{ grafana_dashboards_dir }}"
    dest: /var/lib/grafana/dashboards
    owner: root
    group: root
    mode: 0644
  notify: restart grafana-server

- name: enable and start grafana-server
  service:
    name: grafana-server
    enabled: true
    state: started
