---
- name: initialize local agent apikey
  shell:
    cmd: |
      set -e
      umask 077
      . venv/bin/activate && bin/server auth add-agent | awk '{print $(NF)}' > /etc/sner-ansible/sner_agent_apikey
    chdir: /opt/sner
    creates: /etc/sner-ansible/sner_agent_apikey
