---
- name: config file
  file:
    path: /etc/sner.yaml
    owner: root
    group: www-data
    mode: 0640
    state: touch
    access_time: preserve
    modification_time: preserve

- name: agent config
  blockinfile:
    path: /etc/sner.yaml
    marker: "# ANSIBLE MARKER {mark} agent config"
    block: |
      agent:
        server: '{{ sner_agent_server_url }}'
        apikey: '{{ sner_agent_apikey }}'
  notify: restart sner-agent@1

- name: enable sner-agent@1 service
  service:
    name: sner-agent@1
    enabled: true
    state: started
