---
- name: install deps
  apt:
    name:
      - git
      - sudo
      - make

- name: checkout from git
  git:
    repo: "{{ repo }}"
    version: "{{ branch }}"
    dest: /opt/sner
    update: false

- name: create venv and install dependencies
  shell:
    cmd: |
      set -e
      make venv
      . venv/bin/activate
      make install-deps
      touch .sner-ansible.venv_installed
    chdir: /opt/sner
    creates: /opt/sner/.sner-ansible.venv_installed
