---
- include: mongodb.yml
- include: cvesearch.yml

- name: enable apache2 proxy
  copy:
    content: |
      Listen 15443
      <VirtualHost _default_:15443>
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/cvesearch-error.log
        CustomLog ${APACHE_LOG_DIR}/cvesearch-access.log combined
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/server.crt
        SSLCertificateKeyFile /etc/apache2/ssl/server.key
        ProxyPass / http://localhost:15000/
        ProxyPassReverse / http://localhost:15000/
      </VirtualHost>
    dest: /etc/apache2/sites-enabled/cvesearch.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  when: enable_proxy
