---
- name: set hostname
  hostname:
    name: "{{ ansible_facts['hostname'] }}"

- name: setup etc/hosts
  template:
    src: hostname/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
