---
- include: elastic_repo.yml
- include: elasticsearch.yml
- include: kibana.yml

- name: http proxy esd
  copy:
    content: |
      ProxyPass /esd http://127.0.0.1:9200
      ProxyPassReverse /esd http://127.0.0.1:9200
    dest: /etc/apache2/conf-enabled/esd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  when: enable_proxy

- name: http proxy kibana
  copy:
    content: |
      ProxyPass /kibana http://127.0.0.1:5601
      ProxyPassReverse /kibana http://127.0.0.1:5601
    dest: /etc/apache2/conf-enabled/kibana.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  when: enable_proxy
