---
- name: set hostname
  hostname:
    name: "{{ ansible_facts['hostname'] }}"

- name: setup etc/hosts
  copy:
    content: |
      # managed file
      127.0.0.1 localhost
      ::1 localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      {{ ansible_facts['default_ipv4']['address'] }} {{ ansible_facts['fqdn'] }} {{ ansible_facts['hostname'] }}
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
