---
- name: install basic packages
  apt:
    name:
      - git
      - mc
      - vim
    state: present

- name: purge basic packages
  apt:
    name:
      - joe
      - nano
      - pico
    state: absent

- name: vimrc.local
  copy:
    src: files/vimrc.local
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: 0644
