---
- name: install postfix
  apt:
    name: postfix
    state: present

- name: configure postfix
  lineinfile:
    path: /etc/postfix/main.cf
    line: "{{ item[0] }} = {{ item[1] }}"
    regexp: "^{{ item[0] }} *="
    state: present
  loop:
    - ['myhostname', "{{ ansible_facts['fqdn'] }}"]
    - ['mydestination', "$myhostname, localhost"]
    - ['inet_interfaces', 'loopback-only']
  notify: restart postfix

- name: configure mailname
  copy:
    dest: /etc/mailname
    content: "{{ ansible_facts['fqdn'] }}\n"
    owner: root
    group: root
    mode: 0644
