---
- name: configure sysctl network hardening
  template:
    src: sysctl_hardnet/sysctl.j2
    dest: "{{ sysctl_hardnet_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload sysctl hardnet
