---
- name: install all in one setup for localhost
  hosts: localhost

  roles:
    - role: sner.install
      vars:
        branch: devel

  tasks:
    - name: install database
      apt:
        name: postgresql-all

    - name: create dev environment
      shell:
        cmd: |
          set -e
          ln -sf ../../extra/git_hookprecommit.sh .git/hooks/pre-commit
          make install-db
          make install-extra
          ./venv/bin/activate && make db
          touch .sner-ansible.devel
        chdir: /opt/sner
        creates: /opt/sner/.sner-ansible.devel
