---
- name: monitoring
  hosts: localhost
  roles:
    - sner.apache2
    - sner.monitoring

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

  tasks:
    - name: configure grafana reverse proxy
      copy:
        content: |
          ProxyPass /grafana http://127.0.0.1:3000/grafana
          ProxyPassReverse /grafana http://127.0.0.1:3000/grafana
        dest: /etc/apache2/conf-enabled/grafana.conf
        owner: root
        group: root
        mode: 0644
      notify: restart apache2
