---
- name: sner agent local deployment
  hosts: localhost

  tasks:
    - import_role:
        name: sner_install

    - name: initialize local agent
      import_role:
        name: sner_agent
        tasks_from: initialize_local_agent.yml

    - import_role:
        name: sner_agent
