---
- name: snerlytics node
  hosts: localhost

  roles:
    - role: sner_apache2
      tags: [proxy]
    - role: snerlytics_auth
      tags: [proxy]
    - role: snerlytics_elk
      tags: [elk]
    - role: snerlytics_cvesearch
      tags: [cvesearch]
