---
- name: simple server and agent deployment
  hosts: localhost
  roles:
    - sner.install
    - sner.apache2
    - sner.server

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

  tasks:
    - name: configure sner proxy
      copy:
        content: |
          ProxyPass /sner http://127.0.0.1:18001/sner
          ProxyPassReverse /sner http://127.0.0.1:18001/sner
        dest: /etc/apache2/conf-enabled/sner.conf
        owner: root
        group: root
        mode: 0644
      notify: restart apache2
