---
- name: install server deps
  apt:
    name:
      - postgresql-all
      - python3-psycopg2

- name: create database and user
  block:
    - name: create databse
      postgresql_db:
        name: sner

    - name: create database user
      postgresql_user:
        name: sner
        password: "{{ sner_server_db_password }}"
  become: true
  become_user: postgres

- name: var storage
  file:
    path: /var/lib/sner
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: config file
  tags: server_config
  file:
    path: /etc/sner.yaml
    owner: root
    group: www-data
    mode: 0640
    state: touch
    access_time: preserve
    modification_time: preserve

- name: server config
  tags: server_config
  vars:
    config_base:
      secret: '{{ sner_server_secret }}'
      # yamllint disable-line rule:line-length
      sqlalchemy_database_uri: 'postgresql://{{ sner_server_db_user }}:{{ sner_server_db_password }}@{{ sner_server_db_host }}/{{ sner_server_db_name }}'
      application_root: '/sner'
    config_real: "{{ config_base | combine(sner_server_config, recursive=True) }}"
  blockinfile:
    path: /etc/sner.yaml
    marker: "# ANSIBLE MARKER {mark} server config"
    block: |
      server:
      {{ config_real | to_nice_yaml(indent=2, sort_keys=False) | indent(2, first=True) }}
  notify: restart sner-server

- name: initialize database
  shell:
    cmd: |
      set -e
      . venv/bin/activate && make db
      touch .sner-ansible.db
    chdir: /opt/sner
    creates: /opt/sner/.sner-ansible.db

- name: enable sner-server service
  service:
    name: sner-server
    enabled: true
    state: started

- name: enable apache2 proxy
  copy:
    content: |
      ProxyPass /sner http://127.0.0.1:18001/sner
      ProxyPassReverse /sner http://127.0.0.1:18001/sner
    dest: /etc/apache2/conf-enabled/sner.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  when: enable_proxy
