---
- name: install server deps
  apt:
    name:
      - postgresql-all
      - python3-psycopg2

- name: create database and user
  block:
    - name: create databse
      postgresql_db:
        name: sner

    - name: create database user
      postgresql_user:
        name: sner
        password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: var storage
  file:
    path: /var/lib/sner
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: config file
  file:
    path: /etc/sner.yaml
    owner: root
    group: www-data
    mode: 0640
    state: touch
    access_time: preserve
    modification_time: preserve

- name: server config
  blockinfile:
    path: /etc/sner.yaml
    marker: "# ANSIBLE MARKER {mark} server config"
    block: |
      server:
        secret: '{{ server_secret }}'
        sqlalchemy_database_uri: 'postgresql://sner:{{ db_password }}@localhost/sner'
        application_root: '/sner'
        session_idletime: 36000
  notify: restart sner-web

- name: initialize database
  shell:
    cmd: |
      set -e
      . venv/bin/activate && make db
      touch .sner-ansible.db
    chdir: /opt/sner
    creates: /opt/sner/.sner-ansible.db

- name: enable sner-web service
  service:
    name: sner-web
    enabled: true
    state: started

- name: enable apache2 proxy
  copy:
    content: |
      ProxyPass /sner http://127.0.0.1:18001/sner
      ProxyPassReverse /sner http://127.0.0.1:18001/sner
    dest: /etc/apache2/conf-enabled/sner.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
  when: enable_proxy
